// Maintainable contract spec (component level) for PLACE ORDER — positive path. The frontend twin of
// the system test's latest/acceptance/PlaceOrderPositiveTest. Driven through the shared test-kit:
// a Backend Stub DSL declares what the backend returns, a Frontend DSL drives the rendered screen.
// The Pact plumbing and the driver wiring live behind the harness, and the canonical pact is
// co-generated by idempotent merge.
//
// Positive and negative live in sibling files (place-order-negative.component.test.tsx), as the
// acceptance suite and backend-java's componentTest split them.
import { describe, it } from 'vitest';
import { componentHarness } from '../../support';

const { backend, frontend } = componentHarness();

describe('PlaceOrder — the backend accepts the order', () => {
  it('shows success message when order is accepted', async () => {
    backend.returnsPlacedOrder().execute();

    await frontend.placeOrder().execute().hasConfirmation('ORD-1');
  });

  it('sends the coupon the user typed', async () => {
    backend.returnsPlacedOrder().withCoupon('SAVE10').execute();

    await frontend.placeOrder().withCoupon('SAVE10').execute().hasConfirmation('ORD-1');
  });
});
