// Maintainable contract spec (component level) for PLACE ORDER — negative paths. The frontend twin of
// the system test's latest/acceptance/PlaceOrderNegativeTest. Driven through the shared test-kit:
// a Backend Stub DSL declares what the backend returns, a Frontend DSL drives the rendered screen.
// The Pact plumbing and the driver wiring live behind the harness, and the canonical pact is
// co-generated by idempotent merge.
//
// Positive and negative live in sibling files (place-order-positive.component.test.tsx), as the
// acceptance suite and backend-java's componentTest split them.
import { describe, it } from 'vitest';
import { componentHarness } from '../../support';

const { backend, frontend } = componentHarness();

// The frontend keeps its OWN copy of these rules (order-validation.ts) and rejects without
// ever calling the backend — which is why no interaction is staged here, and why the harness
// points the app at a dead address: if it did call out, the test would fail.
//
// order-validation.unit.test.ts already covers the rule table. What can only be seen here is
// the wiring: that the form runs the validator at all, and that what it produces reaches the
// screen against the right field.
describe('PlaceOrder — the frontend rejects bad input without asking the backend', () => {
  it('reports an empty SKU', async () => {
    await frontend
      .placeOrder()
      .withSku('')
      .execute()
      .hasFieldError('sku', 'SKU must not be empty');
  });

  it('reports a non-integer quantity', async () => {
    await frontend
      .placeOrder()
      .withQuantity('3.5')
      .execute()
      .hasFieldError('quantity', 'Quantity must be an integer');
  });

  it('reports a zero quantity', async () => {
    await frontend
      .placeOrder()
      .withQuantity(0)
      .execute()
      .hasFieldError('quantity', 'Quantity must be positive');
  });

  it('reports an empty country', async () => {
    await frontend
      .placeOrder()
      .withCountry('')
      .execute()
      .hasFieldError('country', 'Country must not be empty');
  });
});

// The existence rules are the backend's to decide — the coupon table answers "does this coupon
// exist", ERP answers "is this a real product", Tax answers "is this country taxable". None of
// them can be reached from the browser, so each rejection has to survive the trip as
// ProblemDetail.errors[] and be rendered against the field it names. One interaction per field the
// UI renders: rename the field on the backend and the contract breaks rather than the screen.
describe('PlaceOrder — the backend rejects against a field', () => {
  it('shows the rejection for a coupon the backend does not know', async () => {
    backend.rejectsPlaceOrderWithUnknownCoupon('INVALIDCOUPON');

    await frontend
      .placeOrder()
      .withCoupon('INVALIDCOUPON')
      .execute()
      .hasFieldError('couponCode', 'Coupon code INVALIDCOUPON does not exist');
  });

  it('shows the rejection for a SKU that is not a product', async () => {
    backend.rejectsPlaceOrderWithUnknownSku('NON-EXISTENT-SKU-12345');

    await frontend
      .placeOrder()
      .withSku('NON-EXISTENT-SKU-12345')
      .execute()
      .hasFieldError('sku', 'Product does not exist for SKU: NON-EXISTENT-SKU-12345');
  });

  it('shows the rejection for a country with no tax rate', async () => {
    backend.rejectsPlaceOrderWithUntaxedCountry('XX');

    await frontend
      .placeOrder()
      .withCountry('XX')
      .execute()
      .hasFieldError('country', 'Country does not exist: XX');
  });
});

// A rejection with no field to hang on: it is the whole order that is refused, so it renders as a
// banner message rather than against an input.
describe('PlaceOrder — the backend rejects the order outright', () => {
  it('shows error message when order is rejected by the backend', async () => {
    backend.rejectsPlaceOrderDuringBlackout();

    await frontend.placeOrder().execute().hasError('Orders cannot be placed on December 31');
  });
});
