sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2699
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.test.*
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S2699
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.spec.*
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S2187
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.spec.*
